import type { Product, Category, Banner } from "@/types"

export const categories: Category[] = [
  {
    id: "1",
    name: "Chair",
    icon: "chair",
    itemCount: 200,
    slug: "chair",
  },
  {
    id: "2",
    name: "Sofa",
    icon: "sofa",
    itemCount: 290,
    slug: "sofa",
  },
  {
    id: "3",
    name: "Table",
    icon: "table",
    itemCount: 140,
    slug: "table",
  },
  {
    id: "4",
    name: "Bed",
    icon: "bed",
    itemCount: 340,
    slug: "bed",
  },
  {
    id: "5",
    name: "Lamp",
    icon: "lamp",
    itemCount: 490,
    slug: "lamp",
  },
]

export const popularProducts: Product[] = [
  {
    id: "p1",
    name: "Armless Solid Dining Chair",
    price: 1250.0,
    image: "/wooden-dining-chair-minimalist-design.jpg",
    category: "chair",
    description: "Elegant wooden dining chair with minimalist design",
    inStock: true,
    rating: 4.5,
    detailedDescription:
      "This elegant armless solid dining chair combines timeless design with modern craftsmanship. Made from premium solid wood, it features a minimalist aesthetic that complements any dining space. The smooth finish and ergonomic design ensure both style and comfort for everyday use.",
    quality: "Premium",
    material: "Solid Oak Wood with Natural Finish",
    dimensions: {
      width: "45cm",
      height: "85cm",
      depth: "50cm",
    },
    weight: "6.5kg",
    colors: ["Natural Wood", "Walnut", "White Oak"],
    features: [
      "Solid wood construction",
      "Ergonomic backrest design",
      "Smooth natural finish",
      "Easy to clean surface",
      "Stackable design",
      "Weight capacity: 120kg",
    ],
    additionalImages: [
      "/wooden-dining-chair-minimalist-design.jpg",
      "/wooden-chair-side-view.jpg",
      "/wooden-chair-back-view.jpg",
      "/wooden-chair-detail-close-up.jpg",
    ],
  },
  {
    id: "p2",
    name: "Elle Decor Roux Arm Chair",
    price: 1250.0,
    image: "/pink-velvet-arm-chair-modern-styling.jpg",
    category: "chair",
    description: "Luxurious pink velvet arm chair with modern styling",
    inStock: true,
    rating: 4.8,
    detailedDescription:
      "The Elle Decor Roux Arm Chair is a statement piece that brings luxury and comfort to any room. Upholstered in premium pink velvet fabric with elegant gold-finished legs, this chair combines contemporary design with classic elegance. Perfect for living rooms, bedrooms, or reading nooks.",
    quality: "Luxury",
    material: "Premium Velvet Upholstery with Gold Metal Legs",
    dimensions: {
      width: "70cm",
      height: "80cm",
      depth: "75cm",
    },
    weight: "12kg",
    colors: ["Pink", "Navy Blue", "Emerald Green", "Grey"],
    features: [
      "Premium velvet upholstery",
      "Gold-finished metal legs",
      "High-density foam cushioning",
      "Curved armrests for comfort",
      "Modern contemporary design",
      "Weight capacity: 150kg",
    ],
    additionalImages: [
      "/pink-velvet-arm-chair-modern-styling.jpg",
      "/pink-velvet-chair-side-angle.jpg",
      "/pink-velvet-chair-armrest-detail.jpg",
      "/pink-velvet-chair-gold-legs-close-up.jpg",
    ],
  },
  {
    id: "p3",
    name: "Elle Decor Roux Arm Chair",
    price: 1250.0,
    image: "/beige-scalloped-arm-chair-elegant.jpg",
    category: "chair",
    description: "Sophisticated beige arm chair with scalloped design",
    inStock: true,
    rating: 4.7,
    detailedDescription:
      "This sophisticated beige arm chair features a unique scalloped backrest design that adds a touch of elegance to any interior. The neutral beige tone makes it versatile for various decor styles, while the plush cushioning ensures maximum comfort. Gold-finished legs complete the luxurious look.",
    quality: "Premium",
    material: "Soft Fabric Upholstery with Gold Metal Frame",
    dimensions: {
      width: "68cm",
      height: "82cm",
      depth: "72cm",
    },
    weight: "11.5kg",
    colors: ["Beige", "Cream", "Light Grey", "Blush Pink"],
    features: [
      "Unique scalloped backrest",
      "Soft fabric upholstery",
      "Gold-finished metal legs",
      "Comfortable padded seat",
      "Elegant curved design",
      "Weight capacity: 140kg",
    ],
    additionalImages: [
      "/beige-scalloped-arm-chair-elegant.jpg",
      "/beige-scalloped-chair-back-view.jpg",
      "/beige-chair-scalloped-detail.jpg",
      "/beige-chair-gold-legs.jpg",
    ],
  },
  {
    id: "p4",
    name: "Elle Decor Roux Arm Chair",
    price: 1250.0,
    image: "/orange-velvet-dining-chair-elegant.jpg",
    category: "chair",
    description: "Bold orange velvet dining chair with elegant lines",
    inStock: true,
    rating: 4.6,
    detailedDescription:
      "Make a bold statement with this vibrant orange velvet dining chair. The rich color and luxurious velvet texture create a focal point in any dining room. Featuring elegant vertical channel tufting and sturdy wooden legs, this chair combines style with durability.",
    quality: "Premium",
    material: "Velvet Upholstery with Solid Wood Legs",
    dimensions: {
      width: "52cm",
      height: "88cm",
      depth: "58cm",
    },
    weight: "9kg",
    colors: ["Orange", "Burgundy", "Mustard Yellow", "Teal"],
    features: [
      "Vertical channel tufting",
      "Rich velvet upholstery",
      "Solid wood legs",
      "High backrest for support",
      "Easy to clean fabric",
      "Weight capacity: 130kg",
    ],
    additionalImages: [
      "/orange-velvet-dining-chair-elegant.jpg",
      "/orange-velvet-chair-side-view.jpg",
      "/orange-chair-tufting-detail.jpg",
      "/orange-chair-wooden-legs.jpg",
    ],
  },
]

export const latestProducts: Product[] = [
  {
    id: "l1",
    name: "Velvet Midnight Natural Sofa",
    price: 1250.0,
    image: "/blue-velvet-modern-sofa-contemporary.jpg",
    category: "sofa",
    description: "Contemporary blue velvet sofa with sleek design",
    inStock: true,
    rating: 4.9,
  },
  {
    id: "l2",
    name: "Modern Furniture",
    price: 1250.0,
    image: "/teal-accent-chair-modern-spaces.jpg",
    category: "chair",
    description: "Stylish teal accent chair for modern spaces",
    inStock: true,
    rating: 4.5,
  },
  {
    id: "l3",
    name: "Modern Furniture Set",
    price: 1250.0,
    image: "/orange-modern-armchair-contemporary.jpg",
    category: "chair",
    description: "Vibrant orange armchair with contemporary flair",
    inStock: true,
    rating: 4.7,
  },
  {
    id: "l4",
    name: "Furniture Sofa Set",
    price: 1250.0,
    image: "/blue-scalloped-accent-chair-elegant.jpg",
    category: "chair",
    description: "Elegant blue scalloped accent chair",
    inStock: true,
    rating: 4.8,
  },
]

export const allProducts: Product[] = [
  {
    id: "a1",
    name: "Modern Table Collection",
    price: 1250.0,
    image: "/yellow-round-coffee-table-wooden-legs.jpg",
    category: "table",
    description: "Bright yellow round coffee table with wooden legs",
    inStock: true,
    rating: 4.4,
  },
  {
    id: "a2",
    name: "Luxury Gold Accent Table",
    price: 1250.0,
    image: "/gold-round-coffee-table-luxury.jpg",
    category: "table",
    description: "Luxurious gold-framed round coffee table",
    inStock: true,
    rating: 4.9,
  },
  {
    id: "a3",
    name: "Classic Table Collection",
    price: 1250.0,
    image: "/wicker-basket-coffee-table-storage.jpg",
    category: "table",
    description: "Unique wicker basket coffee table with storage",
    inStock: true,
    rating: 4.3,
  },
  {
    id: "a4",
    name: "Furniture & Dining Sets",
    price: 1250.0,
    image: "/gold-pedestal-side-table-elegant.jpg",
    category: "table",
    description: "Elegant gold pedestal side table",
    inStock: true,
    rating: 4.6,
  },
  {
    id: "a5",
    name: "Losh Design Lamp",
    price: 1250.0,
    image: "/black-gold-table-lamp-sophisticated.jpg",
    category: "lamp",
    description: "Sophisticated black and gold table lamp",
    inStock: true,
    rating: 4.7,
  },
  {
    id: "a6",
    name: "Ofula Glass Lamp",
    price: 1250.0,
    image: "/crystal-glass-table-lamp-elegant.jpg",
    category: "lamp",
    description: "Elegant crystal glass table lamp",
    inStock: true,
    rating: 4.8,
  },
  {
    id: "a7",
    name: "Best Bedroom Lamp",
    price: 1250.0,
    image: "/brass-cylinder-table-lamp-modern.jpg",
    category: "lamp",
    description: "Modern brass cylinder table lamp",
    inStock: true,
    rating: 4.5,
  },
  {
    id: "a8",
    name: "Furniture & Dining Sets",
    price: 1250.0,
    image: "/wooden-tripod-table-lamp.jpg",
    category: "lamp",
    description: "Scandinavian wooden tripod table lamp",
    inStock: true,
    rating: 4.6,
  },
]

export const banners: Banner[] = [
  {
    id: "b1",
    title: "Explore Our Luxurious Sofa Set Collection",
    subtitle: "Up to 25% Discount",
    description: "Transform your living space with our premium sofa collection",
    image: "/luxury-sofa-set-living-room.jpg",
    buttonText: "Shop Now",
    buttonLink: "/products/sofa",
    backgroundColor: "#d4e4f0",
  },
  {
    id: "b2",
    title: "New Combo Collection",
    subtitle: "Special Offer",
    description: "Complete your home with our curated furniture sets",
    image: "/modern-furniture-combo-set.jpg",
    buttonText: "Shop Now",
    buttonLink: "/products/combo",
    backgroundColor: "#3d4f63",
  },
]
